[program:hermes-gateway-demo]
command=sudo -E hermes -p demo gateway
directory=/home/gem
user=gem
environment=HOME="/home/gem"
autorestart=true
stdout_logfile=%(ENV_LOG_DIR)s/hermes-gateway-demo.log
stderr_logfile=%(ENV_LOG_DIR)s/hermes-gateway-demo-error.log
