[program:worker]
command=bash -c 'export UV_VENV_DIR="venv" &&  sudo -E uv run --active --project /usr/local/lib/hermes-agent python worker.py'
directory=/opt/jupyter/src/
environment=HOME="/home/gem",PYTHONUNBUFFERED="1"
autorestart=true
priority=850
user=gem
stdout_logfile=%(ENV_LOG_DIR)s/tot-access.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=10
stderr_logfile=%(ENV_LOG_DIR)s/tot-error.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=10
